### ISSUE TITLE
Modbus protocol spec

### ISSUE THREAD

**Issue by gagara** [robgt978/Easun-SMG-II-11Kw-esphome-#1]
Hello,

And thanks, for the config for new Easun 11kW inverter.
I'm currently trying to make it work with Home Assistant.
I'm looking for modbus protocol spec for this model as some parameters are missing in your config.
Do you have complete protocol doc?

Thanks.

**Comment by gagara** [comment]
Can you please, repost the link? I can't open it.
Thanks

**Comment by gagara** [comment]
Never mind. Got it.
Thanks a lot!

**Comment by robgt978** [comment]
send me your email, I can't attach the file here

________________________________

**Comment by robgt978** [comment]
this is in chinese

________________________________

**Comment by gagara** [comment]
You can open https://github.com/robgt978/Easun-SMG-II-11Kw-esphome-/issues/1 in browser and post your message directly in github (not via email).
Here you can attach a file or post a link to it.
FYI: I'm currently translating your Italian doc to English and updating my configs. It would be good to have original doc and translate it directly to English.
Thanks.

**Comment by gagara** [comment]
@robgt978, I've re-translated your Italian version to English and published it at https://github.com/gagara/easun-smg-ii-ha-config
Thanks.
